#!/bin/sh
# Oracle Rman Backup Script

export ORACLE_HOME= # ORACLE_HOME
export ORACLE_SID= # 오라클 SID명
export TNS_ADMIN=$ORACLE_HOME/network/admin # tnsnames.ora 위치
export NLS_LANG= # 오라클 케릭터셋.

LANG=C
DATE=`date '+%y%m%d%H'`

BASE_DIR='/backup/oracle/'  # 백업 메인 경로
BACKUP_DIR=$BASE_DIR$DATE   # 백업 일자별 경로 
LOG_DIR='$BASE_DIR/LOG'     # 백업 로그 경로 

DAT_FORMAT=$BACKUP_DIR'/F_%d_%T_%p_%t_datafile_%s'   # DATA 백업형식
CFG_FORMAT=$BACKUP_DIR'/F_%d_%T_%p_%t_control_%s'		 # 아카이브 백업 형식
ARC_FORMAT=$BACKUP_DIR'/F_%d_%T_%p_%t_arch_log_%s'   # 컨트롤파일 백업 형식

CMDFILE='$BASE_DIR/backup_rman.sh'

LOGFILE=$LOG_DIR'/'$DATE'.log'

# FULL BACKUP -----------------------------------------------------------------------------------
ECHO "RUN { " >> $CMDFILE
ECHO " " >> $CMDFILE
ECHO "    CONFIGURE DEVICE TYPE DISK PARALLELISM 1 BACKUP TYPE TO BACKUPSET;" >> $CMDFILE
ECHO "    CONFIGURE DATAFILE BACKUP COPIES FOR DEVICE TYPE DISK TO 1; " >> $CMDFILE
ECHO "    CONFIGURE ARCHIVELOG BACKUP COPIES FOR DEVICE TYPE DISK TO 1; " >> $CMDFILE
ECHO " " >> $CMDFILE
ECHO " " >> $CMDFILE
ECHO "    CROSSCHECK COPY OF ARCHIVELOG ALL; " >> $CMDFILE
ECHO "    CROSSCHECK BACKUP; " >> $CMDFILE
ECHO "    DELETE NOPROMPT EXPIRED COPY; " >> $CMDFILE
ECHO "    DELETE NOPROMPT OBSOLETE REDUNDANCY 1; " >> $CMDFILE
ECHO "    SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT'; " >> $CMDFILE
ECHO "    BACKUP INCREMENTAL LEVEL 0  DATABASE FILESPERSET 5 FORMAT '"$DAT_FORMAT"' TAG 'FULL_BACKUP_DBF_WEEKLY'  SKIP INACCESSIBLE ; " >> $CMDFILE
ECHO "    SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT'; " >> $CMDFILE
ECHO "    BACKUP ARCHIVELOG ALL NOT BACKED UP 1 TIMES FILESPERSET 20 FORMAT '"$ARC_FORMAT"'  TAG 'FULL_BACKUP_ARC_LOGS' SKIP INACCESSIBLE; " >> $CMDFILE
ECHO "                SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT'; " >> $CMDFILE
ECHO "    BACKUP CURRENT CONTROLFILE FORMAT '"$CFG_FORMAT"' TAG 'FULL_BACKUP_CONTROL_FILE'; " >> $CMDFILE
ECHO "    CROSSCHECK BACKUP; " >> $CMDFILE
ECHO "    DELETE NOPROMPT ARCHIVELOG ALL BACKED UP 1 TIMES TO DEVICE TYPE DISK; " >> $CMDFILE
ECHO "    DELETE NOPROMPT OBSOLETE REDUNDANCY 1; " >> $CMDFILE
ECHO "    " >> $CMDFILE
ECHO "    }" >> $CMDFILE
#-------------------------------------------------------------------------------------------------------------

# 증분백업 (INCREMENTAL LEVEL 1 ) ----------------------------------------------------------------------------

ECHO "RUN {" >> $CMDFILE
ECHO " " >> $CMDFILE
ECHO "    CONFIGURE DEVICE TYPE DISK PARALLELISM 1 BACKUP TYPE TO BACKUPSET; " >> $CMDFILE
ECHO "    CONFIGURE DATAFILE BACKUP COPIES FOR DEVICE TYPE DISK TO 1; " >> $CMDFILE
ECHO "    CONFIGURE ARCHIVELOG BACKUP COPIES FOR DEVICE TYPE DISK TO 1; " >> $CMDFILE
ECHO " " >> $CMDFILE
ECHO " " >> $CMDFILE
ECHO "    CROSSCHECK COPY OF ARCHIVELOG ALL; " >> $CMDFILE
ECHO "    DELETE NOPROMPT EXPIRED COPY; " >> $CMDFILE
ECHO "    DELETE NOPROMPT OBSOLETE REDUNDANCY 1; " >> $CMDFILE
ECHO "    SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT'; " >> $CMDFILE
ECHO "    BACKUP INCREMENTAL LEVEL 1 CUMULATIVE DATABASE  FILESPERSET 5 FORMAT '"$DAT_FORMAT"' TAG 'INCR_BACKUP'  SKIP INACCESSIBLE ; " >> $CMDFILE
ECHO "    SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT'; " >> $CMDFILE
ECHO "    BACKUP ARCHIVELOG ALL NOT BACKED UP 2 TIMES FILESPERSET 20 FORMAT '"$ARC_FORMAT"'  TAG 'INCR_BACKUP_ARC_LOGS' SKIP INACCESSIBLE; " >> $CMDFILE
ECHO "                SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT'; " >> $CMDFILE
ECHO "    BACKUP CURRENT CONTROLFILE FORMAT '"$CFG_FORMAT"' TAG 'INCR_BACKUP_CONTROL_FILE'; " >> $CMDFILE
ECHO "    " >> $CMDFILE
ECHO "    }" >> $CMDFILE
#-------------------------------------------------------------------------------------------------------------

rman target / cmdfile=$CMDFILE log=$LOGFILE
